[2022-03-20 10:34:40,226] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: user_processing.processing_user 2022-03-20T08:23:59.186139+00:00 [queued]>
[2022-03-20 10:34:40,321] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: user_processing.processing_user 2022-03-20T08:23:59.186139+00:00 [queued]>
[2022-03-20 10:34:40,323] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2022-03-20 10:34:40,323] {taskinstance.py:1068} INFO - Starting attempt 2 of 2
[2022-03-20 10:34:40,323] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2022-03-20 10:34:40,650] {taskinstance.py:1087} INFO - Executing <Task(PythonOperator): processing_user> on 2022-03-20T08:23:59.186139+00:00
[2022-03-20 10:34:40,655] {standard_task_runner.py:52} INFO - Started process 19439 to run task
[2022-03-20 10:34:40,685] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'user_processing', 'processing_user', '2022-03-20T08:23:59.186139+00:00', '--job-id', '24', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpzwvrvoiu', '--error-file', '/tmp/tmpql8gd9qw']
[2022-03-20 10:34:40,686] {standard_task_runner.py:77} INFO - Job 24: Subtask processing_user
[2022-03-20 10:34:40,897] {logging_mixin.py:104} INFO - Running <TaskInstance: user_processing.processing_user 2022-03-20T08:23:59.186139+00:00 [running]> on host airflowvm
[2022-03-20 10:34:41,085] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=processing_user
AIRFLOW_CTX_EXECUTION_DATE=2022-03-20T08:23:59.186139+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-03-20T08:23:59.186139+00:00
[2022-03-20 10:34:41,315] {python.py:151} INFO - Done. Returned value was: None
[2022-03-20 10:34:41,358] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=processing_user, execution_date=20220320T082359, start_date=20220320T103440, end_date=20220320T103441
[2022-03-20 10:34:41,471] {taskinstance.py:1245} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-03-20 10:34:41,496] {local_task_job.py:151} INFO - Task exited with return code 0
